### PR TITLE
Merge branch Benchmarks

### PR DESCRIPTION
**Pull request by piyueh**

### CODE REVIEW

**Comment by gforsyth** [comment]
Why are all the commits doubled ?

**Comment by piyueh** [comment]
Oh, I didn't notice it...I guess it may be the problem of `bfs`.

I used `bfs` to clean unnecessary and large files in commit history. After that, I encountered a conflict when I want to push my local data to GitHub. Git suggested me to merge the same branch on GitHub to the corresponding local one and then push again.

So I think that's may be the reason.

**Comment by gforsyth** [comment]
If you use a tool like `bfg` or `git-filter-branch` to rewrite history, you need to force push to update.  At this point, I don't think those big files have been removed, since you merged them all back in, you just have a doubled commit history where half of the commits don't have the large files and the other half do.  You need to have one of us at least look at these PRs before merging them in.

**Comment by gforsyth** [comment]
I'll help clean this up when you're back from SF.

**Comment by labarba** [comment]
I had the same thought when I saw the quick merge: the PR should be merged only after a +1 by another team member.

**Pull request merged**
